export const NavLinks = [
  {
    name: "Home",
    path: "/",
  },
  {
    name: "Cars",
    path: "/cars",
  },
  {
    name: "About",
    path: "/about",
  },
  {
    name: "Contact",
    path: "/contact",
  },
];

export const Locations = [
  { name: "Alexandria", carsNum: 5 },
  { name: "Aswan", carsNum: 2 },
  { name: "Asyut", carsNum: 4 },
  { name: "Beheira", carsNum: 1 },
  { name: "Beni Suef", carsNum: 3 },
  { name: "Cairo", carsNum: 5 },
  { name: "Dakahlia", carsNum: 2 },
  { name: "Damietta", carsNum: 4 },
  { name: "Faiyum", carsNum: 1 },
  { name: "Gharbia", carsNum: 3 },
  { name: "Giza", carsNum: 5 },
  { name: "Ismailia", carsNum: 2 },
  { name: "Kafr El Sheikh", carsNum: 4 },
  { name: "Luxor", carsNum: 1 },
  { name: "Matruh", carsNum: 3 },
  { name: "Minya", carsNum: 5 },
  { name: "Monufia", carsNum: 2 },
  { name: "New Valley", carsNum: 4 },
  { name: "North Sinai", carsNum: 1 },
  { name: "Port Said", carsNum: 3 },
  { name: "Qalyubia", carsNum: 5 },
  { name: "Qena", carsNum: 2 },
  { name: "Red Sea", carsNum: 4 },
  { name: "Sharqia", carsNum: 1 },
  { name: "Sohag", carsNum: 3 },
  { name: "South Sinai", carsNum: 5 },
  { name: "Suez", carsNum: 2 },
];

export const Cars = [
  {
    id: 1,
    name: "Audi A4",
    image: "1.png",
    doors: 4,
    passengers: 5,
    price: "110$",
    model: 2021,
    description:
      "The Audi A4 is a luxurious sedan known for its elegant design and advanced technology.",
    type: "Sedan",
    fuelType: "Gasoline",
    gearbox: "Automatic",
    color: "Black",
    features: [
      "Virtual Cockpit",
      "Bang & Olufsen Sound System",
      "Adaptive Cruise Control",
    ],
  },
  {
    id: 2,
    name: "Chevrolet Captiva",
    image: "2.png",
    doors: 5,
    passengers: 7,
    price: "80$",
    model: 2022,
    description:
      "The Chevrolet Captiva is a spacious SUV offering ample room for passengers and cargo.",
    type: "SUV",
    fuelType: "Gasoline",
    gearbox: "Automatic",
    color: "White",
    features: ["Apple CarPlay", "Android Auto", "Rearview Camera"],
  },
  {
    id: 3,
    name: "Hyundai i10",
    image: "3.png",
    doors: 4,
    passengers: 4,
    price: "60$",
    model: 2020,
    description:
      "The Hyundai i10 is a compact and fuel-efficient city car ideal for urban driving.",
    type: "Compact",
    fuelType: "Gasoline",
    gearbox: "Manual",
    color: "Blue",
    features: [
      "Air Conditioning",
      "Bluetooth Connectivity",
      "Front Power Windows",
    ],
  },
  {
    id: 4,
    name: "Hyundai Elantra",
    image: "4.png",
    doors: 4,
    passengers: 4,
    price: "95$",
    model: 2023,
    description:
      "The Hyundai Elantra is a stylish and practical sedan offering a comfortable ride and modern features.",
    type: "Sedan",
    fuelType: "Gasoline",
    gearbox: "Automatic",
    color: "Silver",
    features: ["Wireless Charging Pad", "Smart Trunk", "Lane Following Assist"],
  },
  {
    id: 5,
    name: "Nissan Sunny",
    image: "5.png",
    doors: 4,
    passengers: 5,
    price: "55$",
    model: 2021,
    description:
      "The Nissan Sunny is a reliable and affordable sedan with a spacious interior and good fuel efficiency.",
    type: "Sedan",
    fuelType: "Gasoline",
    gearbox: "Automatic",
    color: "Red",
    features: ["Remote Engine Start", "Cruise Control", "Keyless Entry"],
  },
  {
    id: 6,
    name: "Hyundai Tucson",
    image: "6.png",
    doors: 5,
    passengers: 5,
    price: "90$",
    model: 2022,
    description:
      "The Hyundai Tucson is a versatile SUV offering a comfortable ride and a wide range of features.",
    type: "SUV",
    fuelType: "Gasoline",
    gearbox: "Automatic",
    color: "Gray",
    features: [
      "Wireless Phone Charging",
      "Blind-Spot Collision-Avoidance Assist",
      "Dual-Zone Climate Control",
    ],
  },
  {
    id: 7,
    name: "Peugeot 508",
    image: "7.png",
    doors: 4,
    passengers: 5,
    price: "74$",
    model: 2023,
    description:
      "The Peugeot 508 is a stylish and luxurious sedan known for its refined interior and smooth ride.",
    type: "Sedan",
    fuelType: "Gasoline",
    gearbox: "Automatic",
    color: "Brown",
    features: [
      "Panoramic Sunroof",
      "Nappa Leather Seats",
      "Advanced Driver Assistance Systems",
    ],
  },
  {
    id: 8,
    name: "Peugeot 5008",
    image: "8.png",
    doors: 5,
    passengers: 7,
    price: "100$",
    model: 2019,
    description:
      "The Peugeot 5008 is a spacious and family-friendly SUV with a modern design and excellent safety features.",
    type: "SUV",
    fuelType: "Gasoline",
    gearbox: "Automatic",
    color: "Black",
    features: ["Third-Row Seating", "Hands-Free Tailgate", "Peugeot i-Cockpit"],
  },
];

export const logos = [
  { name: "audi", url: "/assets/images/logos/audi.png" },
  { name: "amg", url: "/assets/images/logos/amg.png" },
  { name: "bently", url: "/assets/images/logos/bently.png" },
  { name: "bmw", url: "/assets/images/logos/bmw.png" },
  { name: "cevro", url: "/assets/images/logos/cevro.png" },
  { name: "ford", url: "/assets/images/logos/ford.png" },
  { name: "hyundai", url: "/assets/images/logos/hyundai.png" },
  { name: "jeep", url: "/assets/images/logos/jeep.png" },
  { name: "lambo", url: "/assets/images/logos/lambo.png" },
  { name: "tesla", url: "/assets/images/logos/tesla.png" },
];
